### ISSUE TITLE
Crashlog Saving Problem

### ISSUE THREAD

**Issue by tigurand** [waicool20/KAGA#11]
Can't save a file with : on file name. Need to change the date time format or I will get this on saving crashlog:

java.nio.file.InvalidPathException: Illegal char <:> at index 21: crashes/2017-01-26 13:28:43.log
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
	at com.waicool20.kaga.KancolleAuto.saveCrashLog(KancolleAuto.kt:66)
	at com.waicool20.kaga.KancolleAuto.handleCrash(KancolleAuto.kt:57)
	at com.waicool20.kaga.KancolleAuto.startAndWait(KancolleAuto.kt:44)
	at com.waicool20.kaga.views.KagaView$onStartStopButton$1.run(KagaView.kt:131)
	at java.lang.Thread.run(Unknown Source)

I also have a request to add a button to clear all log files, or maybe an option to enable/disable saving log.

**Comment by waicool20** [comment]
Hmm didn't know windows didn't allow colons in filenames, anyways fixed in e94ade3f16c7319f7bae4b7ad44ac6bb666465b0

I think I'll add a button to clear all logs as opposing to disabling logs outright as they are always useful.

**Comment by waicool20** [comment]
Button added in 3124378728de9a2f11d1d42ff317ad89efc93582
Can be found in Files > Clear all crash logs
