### ISSUE TITLE
Problems with creating new kaga.json file

### ISSUE THREAD

**Issue by asdf1324** [waicool20/KAGA#37]
When I try to launch KAGA without kaga.json in my kaga folder :

*KAGA Location*>java -jar KAGA.jar
[KAGA] [2017-06-21 00:19:53] [c.w.k.KagaApp] INFO - Starting KAGA
[KAGA] [2017-06-21 00:19:53] [c.w.k.c.KagaConfig$Loader] INFO - Attempting to load KAGA configuration
[KAGA] [2017-06-21 00:19:53] [c.w.k.c.KagaConfig$Loader] WARN - No valid Json configuration was found, error: No content
 to map due to end-of-input
 at [Source: *KAGA Location*\kaga\kaga.json; line: 1, column: 0]
[KAGA] [2017-06-21 00:19:53] [c.w.k.c.KagaConfig$Loader] INFO - Using a default configuration
Exception in Application start method
June 21, 2017 12:19:53 AM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StackOverflowError
        at java.lang.Exception.<init>(Unknown Source)
        at sun.nio.fs.WindowsException.<init>(Unknown Source)
        at sun.nio.fs.WindowsNativeDispatcher.FindFirstFile0(Native Method)
        at sun.nio.fs.WindowsNativeDispatcher.FindFirstFile(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(Unknown Source)
        at java.nio.file.Files.exists(Unknown Source)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:114)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load(KancolleAutoProfile.kt:149)
        at com.waicool20.kaga.config.KancolleAutoProfile$Loader.load$default(KancolleAutoProfile.kt:113)

1.6.0 works well but from 1.7.0 does not work properly.

**Comment by waicool20** [comment]
Ahh i see the problem, ill write a quick fix

**Comment by waicool20** [comment]
Fixed in 5a60b02047cd339b69ac426c98ad96f135feaabd

**Comment by waicool20** [comment]
Bug fix release: https://github.com/waicool20/KAGA/releases/tag/v1.7.2
